package com.hangman;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * 
 * @author Marcos Abreu
 * Main class of JUNIT.
 */
@SpringBootTest
class HangmanApplicationTests {

	@Test
	void contextLoads() {
		/**
		 * Generated by Spring Boot
		 */
	}

}
